server:
  port: 8080
spring:
  datasource:
    url: ${HELTFIT_DB_URL}
    username: ${HELTFIT_DB_USER}
    password: ${HELTFIT_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
